### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shanow7** [noualibechir/rag_osint#1]
Traceback (most recent call last):
  File "/root/Desktop/OSINT/rag_osint/.env/bin/streamlit", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Desktop/OSINT/rag_osint/.env/lib/python3.11/site-packages/streamlit/web/cli.py", line 234, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/root/Desktop/OSINT/rag_osint/.env/lib/python3.11/site-packages/streamlit/web/cli.py", line 270, in _main_run
    bootstrap.run(file, is_hello, args, flag_options)
  File "/root/Desktop/OSINT/rag_osint/.env/lib/python3.11/site-packages/streamlit/web/bootstrap.py", line 401, in run
    asyncio.run(run_server())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/Desktop/OSINT/rag_osint/.env/lib/python3.11/site-packages/streamlit/web/bootstrap.py", line 389, in run_server
    await server.start()
  File "/root/Desktop/OSINT/rag_osint/.env/lib/python3.11/site-packages/streamlit/web/server/server.py", line 269, in start
    start_listening(app)
  File "/root/Desktop/OSINT/rag_osint/.env/lib/python3.11/site-packages/streamlit/web/server/server.py", line 129, in start_listening
    start_listening_tcp_socket(http_server)
  File "/root/Desktop/OSINT/rag_osint/.env/lib/python3.11/site-packages/streamlit/web/server/server.py", line 196, in start_listening_tcp_socket
    http_server.listen(port, address)
  File "/root/Desktop/OSINT/rag_osint/.env/lib/python3.11/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
              ^^^^^^^^^^^^^
  File "/root/Desktop/OSINT/rag_osint/.env/lib/python3.11/site-packages/tornado/netutil.py", line 105, in bind_sockets
    socket.getaddrinfo(address, port, family, socket.SOCK_STREAM, 0, flags),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

can you help?

**Comment by silsicksix** [comment]
try just running `streamlit run app.py ` instead.

**Comment by shanow7** [comment]
thx :)
